# -*- coding: utf-8 -*-
"""Text-To-Image Generator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DT8cDaBPwNoBOpBxKCgvZf_LGurhAXil
"""

!pip install --upgrade diffusers transformers -q

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cuXX

from pathlib import Path
import tqdm
import torch
import pandas as pd
import numpy as np
from diffusers import StableDiffusionPipeline
from transformers import pipeline, set_seed
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import cv2

class CFG:
    device = "cuda"
    seed = 42
    generator = torch.Generator(device).manual_seed(seed)
    image_gen_steps = 35
    image_gen_model_id = "stabilityai/stable-diffusion-2"
    image_gen_size = (400,400)
    image_gen_guidance_scale = 9
    prompt_gen_model_id = "gpt2"
    prompt_dataset_size = 6
    prompt_max_length = 12

from pathlib import Path
import tqdm
import torch
import pandas as pd
import numpy as np
from diffusers import StableDiffusionPipeline
from transformers import pipeline, set_seed
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import cv2

class CFG:
    device = "cuda"
    seed = 42
    generator = torch.Generator(device).manual_seed(seed)
    image_gen_steps = 35
    image_gen_model_id = "stabilityai/stable-diffusion-2"
    image_gen_size = (400,400)
    image_gen_guidance_scale = 9
    prompt_gen_model_id = "gpt2"
    prompt_dataset_size = 6
    prompt_max_length = 12

image_gen_model = StableDiffusionPipeline.from_pretrained(
    CFG.image_gen_model_id, torch_dtype = torch.float16,
    varient = "fp16", use_auth_token='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', guidance_scale=9
)
image_gen_model = image_gen_model.to(CFG.device)


def generate_image(prompt,model):
    image = model(
        prompt, num_interface_steps=CFG, image_gen_steps=CFG.image_gen_steps,
        generator=CFG.generator,
        guidance_scale=CFG.image_gen_guidance_scale
    ).images[0]

    image = image.resize(CFG.image_gen_size)
    return image

# Example usage
prompt = "a beautiful mountain landscape"
image = generate_image(prompt, image_gen_model)
plt.imshow(image)
plt.axis('off')
plt.show()

prompt = "a beautiful woman landscape"
image = generate_image(prompt, image_gen_model)
plt.imshow(image)
plt.axis('off')
plt.show()